[container.image]
repository="sabthar" # Ex - Docker hub repository name.
name="sse" # Container name
tag="v0.1.0"

[cloud.deployment]
min_memory="100Mi" # Minimum memory required for the container.
max_memory="100Mi" # Maximum memory a single container can take.
min_cpu="500m"  # Minimum CPU required for the container.
max_cpu="500m" # Maximum CPU a single container can take.

[settings]
buildImage=true 